import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

# --- 1. Data Loading and Caching ---
# This function loads the pre-structured data.
# The @st.cache_data decorator makes the app fast by loading the data only once.
@st.cache_data
def load_bop_data(filepath="BOP_quad_analysis.csv"):
    """Loads the pre-structured BOP data from the CSV file."""
    try:
        df = pd.read_csv(filepath)
        # Ensure the 'Quarter' column is treated as a string for plotting stability
        df['Quarter'] = df['Quarter'].astype(str)
        return df
    except FileNotFoundError:
        return None

# --- 2. The Core Plotting Function for the Detailed View ---
def create_detailed_bop_figure(df_single_country: pd.DataFrame, country_name: str):
    """
    Creates an interactive Plotly figure for a single country's detailed BOP.

    Args:
        df_single_country (pd.DataFrame): The DataFrame containing data for ONLY one country.
        country_name (str): The full name of the country for the title.

    Returns:
        A Plotly Figure object.
    """
    df_plot = df_single_country.copy()

    # Calculate the financing line which is the inverse of the Overall Balance
    df_plot['Financing'] = -1 * df_plot['Overall Balance']

    # Define the exact column names as they appear in your CSV
    components_to_plot = [
        'Goods Balance', 'Services Balance', 'Primary Income', 'Secondary Income',
        'Capital Account', 'Net Errors & Omissions',
        'Direct Investment', 'Portfolio Investment', 'Financial Derivatives', 'Other Investment'
    ]

    # Create cleaner names for the legend by removing leading/trailing spaces
    legend_names = [name.strip() for name in components_to_plot]

    colors = {
        'Goods Balance': '#e74c3c', 'Services Balance': '#d35400', 'Primary Income': '#c0392b', 'Secondary Income': '#f1c40f',
        'Capital Account': '#f39c12', 'Net Errors & Omissions': '#7f8c8d',
        'Direct Investment': '#27ae60', 'Portfolio Investment': '#2ecc71', 'Financial Derivatives': '#1abc9c', 'Other Investment': '#3498db'
    }

    fig = go.Figure()

    for component, legend_name in zip(components_to_plot, legend_names):
        if component in df_plot.columns:
            fig.add_trace(go.Bar(
                x=df_plot['Quarter'],
                y=df_plot[component],
                name=legend_name,
                marker_color=colors.get(component)
            ))

    fig.add_trace(go.Scatter(
        x=df_plot['Quarter'],
        y=df_plot['Overall Balance'],
        mode='lines+markers',
        name='Overall Balance (Sum of Bars)',
        line=dict(color='#34495e', width=3),
        marker=dict(size=8)
    ))
    
    fig.add_trace(go.Scatter(
        x=df_plot['Quarter'],
        y=df_plot['Financing'],
        mode='markers',
        name='Financing (Opposite of Overall Balance)',
        marker=dict(symbol='x-thin', size=12, color='#8e44ad', line=dict(width=2))
    ))

    fig.update_layout(
        barmode='relative', 
        title_text=f"Desglose de Balanza de Pagos: {country_name}",
        xaxis_title="Cuatrimestre. Fuente: Balanza de Pagos según metodología FMI",
        yaxis_title="Expresado en Billones de USD",
        legend_title="Componente BOP",
        template="plotly_white",
        height=700,
        xaxis_tickangle=-45,
        legend=dict(traceorder='normal'),
        yaxis=dict(
            tickformat="$",
            ticksuffix="B"
        )
    )
    fig.add_hline(y=0, line_dash="dash", line_color="black", line_width=1)
    
    return fig

# --- Main Streamlit App Body ---

st.set_page_config(layout="wide")
st.title("Análisis Interactivo de la Balanza de Pagos")

# Load the data generated by your other script
bop_data = load_bop_data()

if bop_data is None:
    st.error("Error: No pude encontrar el archivo 'BOP_Structured_Quarterly_Analysis.csv'.")
    st.write("Por favor, ejecuta primero tu script de procesamiento de datos para crear este archivo y colócalo en el mismo directorio que esta aplicación Streamlit.")
else:
    all_countries = sorted(bop_data['Country_Name'].unique())
    
    # --- Part 1: Single Country Detailed View ---
    st.header("Desglose Detallado por País")

    country_to_show = st.selectbox(
        'Selecciona un país para ver el desglose detallado:',
        options=all_countries
    )

    if country_to_show:
        # Filter the main DataFrame for the selected country
        df_single = bop_data[bop_data['Country_Name'] == country_to_show]
        
        # Generate and display the plot using our dedicated function
        detailed_fig = create_detailed_bop_figure(df_single, country_to_show)
        st.plotly_chart(detailed_fig, use_container_width=True)

    # --- Part 2: Multi-Country Comparison ---
    if len(all_countries) > 1:
        st.header("Comparación del Saldo General")
        
        selected_countries = st.multiselect(
            'Selecciona los países a comparar:',
            options=all_countries,
            default=all_countries
        )

        if selected_countries:
            df_multi_filtered = bop_data[bop_data['Country_Name'].isin(selected_countries)]
            
            fig_multi = px.line(
                df_multi_filtered,
                x='Quarter',
                y='Overall Balance',
                color='Country_Name',
                markers=True,
                labels={'Overall Balance': 'Balanza de Pagos (Expresado en Billones de USD)', 'Quarter': 'Cuatrimestre. Fuente: Balanza de Pagos según metodología FMI'},
                title='Comparación del Saldo de Balanza de Pagos Trimestral'
            )
            fig_multi.add_hline(y=0, line_dash="dash", line_color="black")
            st.plotly_chart(fig_multi, use_container_width=True)

    # --- Part 3: Data Table and Download ---
    st.header("Mira la tabla y descárgala")
    st.write("La tabla a continuación muestra los datos estructurados utilizados para generar estos gráficos.")

    # Display the full data table in the app
    st.dataframe(bop_data)

    # Provide a download button for the CSV
    @st.cache_data
    def convert_df_to_csv(df):
        return df.to_csv(index=False).encode('utf-8')

    csv_to_download = convert_df_to_csv(bop_data)

    st.download_button(
       label="Descarga la tabla completa de BOP como un CSV",
       data=csv_to_download,
       file_name="BOP_Structured_Quarterly_Analysis.csv",
       mime="text/csv",
    )